name: Java Maven Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21" # Replace with the actual version

      - name: Install dependencies
        run: mvn install
      - name: Build with Maven
        run: mvn -B clean install
      - name: Run Tests
        run: mvn test
